### ISSUE TITLE
errors 

### ISSUE THREAD

**Issue by V33RU** [danicuestasuarez/overflow-checker#1]
testi@ICS:~/overflow-checker$ sudo python3 overflow_checker.py -m 99999 /home/testi/overflow-checker/test_files/pwn1
Traceback (most recent call last):
  File "overflow_checker.py", line 104, in <module>
    main()
  File "overflow_checker.py", line 93, in main
    if (insaneOverflow()):
  File "overflow_checker.py", line 45, in insaneOverflow
    return overflow(max)
  File "overflow_checker.py", line 32, in overflow
    timeout=0.1)
  File "/usr/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './/home/testi/overflow-checker/test_files/pwn1': './/home/testi/overflow-checker/test_files/pwn1'

**Comment by daniel-cues** [comment]
Absolute paths not supported
